### ISSUE TITLE
Issue with monitor

### ISSUE THREAD

**Issue by ChrisJMarais** [intersystems/TestCoverage#10]
Hi,

We are getting the following error when running tests... These tests were run before without any issues.
What can be the cause of this, I have tested this in CACHE 2018, Ensemble 2016.2, and IRIS For Health 2021.1, they all have the same issue.

I can not find any results searching for this on the internet.

![image](https://user-images.githubusercontent.com/13786405/141695844-6d106a6b-6846-46a0-a9b9-737dbbc88b2f.png)

**Comment by isc-tleavitt** [comment]
Also discussed here: https://community.intersystems.com/post/errors-when-using-testcoverage-somebody-else-using-monitor

This message means that ^PERFMON or ^%SYS.MONLBL is already running somewhere on the system. If you do ^%SYS.MONLBL it should provide some helpful output/options.

I think let's leave this open as an issue with TestCoverage to make it more helpful in these situations, if possible.

**Comment by isc-tleavitt** [comment]
Part of the root cause, via direct message on Developer Community from @ChrisJMarais:
---
I have one method that looks like this... We would expand the method in the training.
```
ClassMethod FizzBuzz() As %String
{
    return 42
}
```
Every time I run this test it broke the monitor, when I changed it to the following it works fine
```
ClassMethod FizzBuzz() As %String 
{ 
    set answer = 42
    return answer
}
```

**Comment by isc-tleavitt** [comment]
That actually makes sense as a root cause. The line by line monitor looks at routine lines, but a method that returns a constant ends up handled entirely in the class descriptor (rather than having .int code associated with it). As a result, for such a method, you'll see that it'll never actually be flagged as covered in the test coverage tool, even if there is a unit test that runs it. (I think we handle this by saying the line can't be covered.)

I think we need to handle the case better (somewhere) where there is not .INT associated with a class - perhaps also in the case where the only class for which coverage is tracked has no associated .INT
