### ISSUE TITLE
Class with 10375 lines not loading in ResultDetailViewer

### ISSUE THREAD

**Issue by psteiwer** [intersystems/TestCoverage#3]
I have a class that is 10375 lines long. It appears that the page stops loading after about 1 minute and ends up not displaying anything. This is almost certainly the CSP Gateway timeout. I put some logging in TestCoverage.UI.Utils:ColoredTextFetch() and it is getting through about 4,000 lines before stopping.

**Comment by psteiwer** [comment]
Tried increasing the CSP Gateway timeout and I got the following:
ERROR #5002: ObjectScript error: <MAXSTRING>%DrawJSON+63^%ZEN.Auxiliary.altJSONSQLProvider.1 [%DrawJSON+63^%ZEN.Auxiliary.altJSONSQLProvider.1:UNIT]
SOURCE ELEMENT: %ZEN.Auxiliary.altJSONSQLProvider (coverageDataProvider)

**Comment by timleavitt** [comment]
There are a few layers to this issue:
* The class query is needlessly slow because it passes the entire result set in an array from Execute to Fetch. It's a simple fix to use ^CacheTemp or a % variable instead.
* %ZEN.Auxiliary.altJSON[SQL]Provider doesn't support outputting JSON that exceeds the maximum string length. The %DrawJSON error you're seeing is actually `<MAXSTRING>` (which I think ended up getting masked in your copy/paste).
* With that resloved, TestCoverage.UI.ResultDetailViewer is still slow, because it runs the query twice on load. (Oops!)
* Even with that resolved, rendering of such a large block of HTML is still slow because it's done all at once via innerHTML rather than via DOM manipulation (which is faster).

All of these things can/should be fixed.
